import json

translation_dict = {
    "The Ascendant": "上昇するもの",
    "As The Sun His Course": "太陽の如きその軌道",
    "The Book of Thrones": "玉座の書",
    "Book of True Blood": "真血の書",
    "A Child's Treasury of Golden Afternoons": "子供の黄金の午後の宝物庫",
    "De Bellis Murorum": "城壁の戦いについて",
    "The Deeds of the Scarred Captain": "傷だらけの船長の功績",
    "De Horis book 2": "時の書 第二巻",
    "De Horis book 3": "時の書 第三巻",
    "Exorcism for Girls": "少女のための悪魔祓い",
    "The High Traditions of the Noble Endeavour": "高貴なる努力の高き伝統",
    "How the End will Begin": "終わりはいかに始まるか",
    "Journal of Sir David Greene, 1903": "デヴィッド・グリーン卿の日記、1903年",
    "The Iron Book": "鉄の書",
    "The Leonine Tantra": "獅子のタントラ",
    "THE OPEN HEAD": "開かれた頭",
    "The Sevenfold Slaying of the Seven-Coiled": "七とぐろの七重の殺戮",
    "Seven Shards": "七つの欠片",
    "The Sky in the Scar": "傷跡の空",
    "The Sun's Lament": "太陽の哀歌",
    "The Victory of Crowns": "王冠の勝利",
    "The War of the Roads, 1451-1551": "道路戦争 1451-1551",
    "The Wound-Wounds": "傷の傷",
    "The Admonitory Automata Project": "訓戒的自動機械計画",
    "The Amalgam of the Red Rose": "赤薔薇の混合物",
    "Ambrosial!": "アンブロシア！",
    "Amiranis Beteli": "アミラニのベテリ",
    "The Book of Cinders": "灰の書",
    "The Book of Dissolution": "溶解の書",
    "The Burning Woman": "燃える女",
    "The Carmine Petal: Revised": "洋紅の花びら：改訂版",
    "The Carmine Petal: Unexpurgated": "洋紅の花びら：無削除版",
    "A Descent of the Shell": "殻の降下",
    "Glimmerings": "かすかな光",
    "The Incandescent Tantra": "白熱のタントラ",
    "Journal of Walter Dewulf": "ウォルター・デウルフの日記",
    "The Manner in which the Alchemist was Spared": "錬金術師がいかにして見逃されたか",
    "The Messenger Awaiting Her Destination": "目的地を待つ使者",
    "My Deeds, My Powers, My Achievements and the Injustices Perpetrated Against Me": "我が功績、我が力、我が達成、そして我に対する不当行為",
    "Old Coppernose and the Softer Metal": "オールド・カッパーノーズとより柔らかい金属",
    "On Matthias and the Amethyst Imago: Transformation": "マティアスと紫水晶の成虫について：変態",
    "A Shape in Smoke": "煙の中の形",
    "Skin of Silver": "銀の皮膚",
    "Sunset Passages": "日没の通路",
    "The Temptations of Architecture": "建築の誘惑",
    "The Vinzant Inscriptions": "ヴィンザントの碑文",
    "Vinzant's Minglings": "ヴィンザントの混合",
    "Calicite Supplications": "カリサイトの嘆願",
    "A Catalogue of Uncharted Pleasures": "未知の喜びの目録",
    "COLOURS IN THE LIVER": "肝臓の色彩",
    "The Devoured Tantra": "貪られたタントラ",
    "The Dream of the Conspiracy of the Lower Skies": "下層の空の陰謀の夢",
    "The Geminiad ii": "双子座の書 ii",
    "An Impertinent Vitulation": "無礼な歓呼",
    "A Journey to the Grove": "木立ちへの旅",
    "The Intimations of Skin": "皮膚の暗示",
    "Medusan Commentaries": "メドゥーサの注釈",
    "On Matthias and the Amethyst Imago: Pursuit": "マティアスと紫水晶の成虫について：追跡",
    "On Thirstlies, Ivories and Lovelies": "渇き、象牙、そして愛らしさについて",
    "One Thousand Threads": "千の糸",
    "The Orchid Transfigurations: a Birth": "蘭の変容：誕生",
    "The Orchid Transfigurations: a Feast": "蘭の変容：祝宴",
    "The Rose of Nuriel": "ヌリエルの薔薇",
    "The Skeleton Songs": "骸骨の歌",
    "Snare of the Tree: Collected Proverbs of Aunt Mopsy": "木の罠：モプシーおばさんのことわざ集",
    "The Sun Disfigured": "傷つけられた太陽",
    "The Thirsting Tantra": "渇きのタントラ",
    "The Tripled Heart": "三重の心臓",
    "The Wind's Ruin": "風の破滅",
    "The Wonderful Shape": "素晴らしい形",
    "Twenty-Six Enticements, Seven Torments": "26の誘惑、7つの苦痛",
    "A True and Complete Accounting of the Asclepian Mysteries of the Roots of the House": "館の根のアルスレピオスの神秘についての真実かつ完全な報告",
    "Apollo and Marsyas": "アポロンとマルシュアス",
    "The Book of the Extinguished Heart": "消えた心臓の書",
    "The Ceaseless Tantra": "絶え間ないタントラ",
    "Commandments For the Preservation of All That Exists": "存在するすべての保存のための戒律",
    "The Flayed Tantra": "剥がされたタントラ",
    "The Geminiad i": "双子座の書 i",
    "The Instruments of the Heart": "心の道具",
    "Lake Fucino Recordings": "フチーノ湖の録音",
    "Notes on Bindings": "装丁に関するメモ",
    "Nyn's Cages (Avignon Text)": "ニンの檻（アヴィニョン版）",
    "The Orchid Transfigurations: Noon": "蘭の変容：正午",
    "The Other Line": "もう一つの血統",
    "Rapt in the King": "王に夢中",
    "Those Who Do Not Sleep": "眠らぬ者たち",
    "The Time of Division": "分裂の時代",
    "Two Wombs, One Heart": "二つの子宮、一つの心臓",
    "Velletri Interviews": "ヴェッレトリのインタビュー",
    "Warming Draughts to Uplift the Heart": "心を高揚させる温かい飲み薬",
    "Advice on Containment": "封じ込めの助言",
    "An Almanac of Entrances": "入り口の年鑑",
    "By Their Marks Shall Ye Know them": "その印によって彼らを知るだろう",
    "Cardea's Delights": "カルデアの喜び",
    "Deaths and their Evasions": "死とその回避",
    "The Elations of Limentinus": "リメンティヌスの歓喜",
    "The Gospel of Zacchaeus": "ザアカイの福音書",
    "The Grand Passage of the Hours": "時の大いなる通過",
    "The Locksmith's Dream: Trespasses": "鍵師の夢：侵入",
    "A Manual for Departure": "出発のマニュアル",
    "OGHKOR OGHKOR TISSILAK OGHKOR": "オグコル オグコル ティシラク オグコル",
    "On Imperfections": "不完全性について",
    "On the Matter and the Deeds of Serpents": "蛇の物質と行為について",
    "On the Winding Stair": "曲がりくねった階段について",
    "The Raptures of Forculus": "フォルクルスの狂喜",
    "The Road to Janus": "ヤヌスへの道",
    "Towards a Fundamental Aesthetic": "根本的な美学に向けて",
    "A Tower Falls": "塔が倒れる",
    "The Twin-Serpent Tantra": "双蛇のタントラ",
    "The Treatise on Underplaces": "地下の場所に関する論文",
    "Travelling at Night, vol 1": "夜の旅、第1巻",
    "Travelling at Night, vol 3": "夜の旅、第3巻",
    "Xenodicene Odes": "ゼノディケの頌歌",
    "The Alloy of the White Rose": "白薔薇の合金",
    "Bancroft Diaries": "バンクロフトの日記",
    "The Chandler's Wish": "蝋燭屋の願い",
    "Gospel of Nicodemus": "ニコデモの福音書",
    "The High Mysteries of the Innermost Chamber of our Church Solar": "我らが太陽教会の最奥の間の高次神秘",
    "In the Malleary": "鍛冶場にて",
    "The Known-Unknown Tantra": "既知と未知のタントラ",
    "Letters To My Successor": "後継者への手紙",
    "A Light in the Inkwell": "インク壺の光",
    "The Locksmith's Dream: a Light through the Keyhole": "鍵師の夢：鍵穴からの光",
    "The Locksmith's Dream: Incursus": "鍵師の夢：襲撃",
    "Opus Magnum Caeruleum": "青き大いなる業",
    "Prophecies of Glory": "栄光の予言",
    "Quirinic Meditations": "クゥイリヌスの瞑想",
    "The Rose of Waznei": "ワズネイの薔薇",
    "The Sky, the Soul": "空、魂",
    "Sunrise Awakenings": "日の出の目覚め",
    "The Sun's Design": "太陽の設計",
    "Unhatched Hymns": "孵化せぬ賛歌",
    "The Watchful Tantra": "見守るタントラ",
    "Wainscot Histories": "羽目板の歴史",
    "The Account of Kanishk at the Spider's Door": "蜘蛛の扉におけるカニシカの報告",
    "The Black Book of Brittany": "ブルターニュの黒き書",
    "Black Nephrite": "黒き軟玉",
    "Codex Acephali": "無頭の写本",
    "Collected Hush House Lectures": "沈黙の家の講義集",
    "The Crossing to Noon": "正午への渡り",
    "The Deaths of the Moon": "月の死",
    "Enchiridion Tragularis": "悲劇の手引書",
    "An Exorcist's Field Manual": "悪魔祓いの野外マニュアル",
    "EXPERIMENT BEYOND SIGHT": "視覚を超える実験",
    "An Investigation of A Foundered Country": "沈んだ国の調査",
    "The Kerisham Portolan": "ケリシャムの海図",
    "The Larquebine Codex": "ラークバインの写本",
    "Malachite Supplications": "孔雀石の嘆願",
    "The Moon's Egg": "月の卵",
    "The Morphy Codex": "モーフィーの写本",
    "Nix Abolix": "ニックス・アボリックス",
    "Observations on the Peacock Door": "孔雀の扉の観察",
    "A Pale Lady and a Prince of Wines": "蒼白の淑女とワインの王子",
    "The Queen's Turn": "女王の番",
    "The Sea Does Not Regret": "海は後悔しない",
    "The Secret Colours": "秘密の色",
    "The Three and the Three (Kerisham Manuscript)": "三と三（ケリシャム写本）",
    "The Three and the Three (St Chiavi Manuscript)": "三と三（聖キアヴィ写本）",
    "The Three and the Three (Vatican Manuscript)": "三と三（バチカン写本）",
    "To a Pale Lady": "蒼白の淑女へ",
    "The Twelve Letters On Consequence": "結果に関する十二通の手紙",
    "The Viennese Conundra": "ウィーンの謎",
    "The Voyages of Ferninshun of Oreol": "オレオル出身のフェルニンシュンの航海",
    "The World Despoil'd": "略奪された世界",
    "What Does Not Bark": "吠えないもの",
    "The Book of Masks": "仮面の書",
    "The Carbonek Schism": "カルボネックの分裂",
    "The Debate of Seven Cups": "七つの杯の議論",
    "An Echo of Silence": "沈黙の反響",
    "The Fire-Circle Tantra": "火の輪のタントラ",
    "Five Creations": "五つの創造",
    "From History to Eternity": "歴史から永遠へ",
    "The Geminiad iii": "双子座の書 iii",
    "Inaam, Kapigiginlupir, Garkie, Cryppys": "イナアム、カピギギンルピル、ガーキー、クリピス",
    "Kitling Ripe and the Moldywarp's Grave (and Other Stories)": "キトリング・ライプとモグラの墓（その他の物語）",
    "Kopralith Omphalos": "コプラリスのへそ",
    "On Matthias and the Amethyst Imago: Loss": "マティアスと紫水晶の成虫について：喪失",
    "Plantagenet Mysteries": "プランタジネットの謎",
    "The Rose of Hypatia": "ヒュパティアの薔薇",
    "The Serenity of the Black Wood": "黒き森の静けさ",
    "The Shaven Lock Tantra": "剃髪のタントラ",
    "The Silver Book": "銀の書",
    "The Six Letters on Necessity": "必然性に関する六通の手紙",
    "The Songs of the Carapace Cross": "甲羅の十字架の歌",
    "White Jade Tablet": "白玉の石板",
    "The Bee-Keeper's Ends": "養蜂家の最期",
    "The Berrybook": "木の実の書",
    "Cucurbit Prisoner Records 1927": "ククルビット囚人記録 1927",
    "De Horis book 1": "時の書 第一巻",
    "De Ratio Quercuum": "樫の木の比率について",
    "Fekri's Herbary": "フェクリの薬草園",
    "Green Jasper Tablet": "緑碧玉の石板",
    "Honey: the Comprehensive Guide": "蜂蜜：総合ガイド",
    "Kitling Ripe's Tasty Treats": "キトリング・ライプの美味しいおやつ",
    "The Most Sorrowful End of the Lady Nonna": "ノンナ姫の最も悲しい最期",
    "Serpent-Root": "蛇の根",
    "The Shadow in the Stair": "階段の影",
    "Three Flowers Hath the Tree": "その木には三つの花がある",
    "The Writing on the Wall": "壁の落書き",
    "Book of Miah": "ミアの書",
    "The Book of the Centipede": "百足の書",
    "The Concursum Diaries": "コンクルスムの日記",
    "The History of Inks": "インクの歴史",
    "Isaac of Karth's History of the Shadowless Kings": "カルスのアイザックによる影なき王たちの歴史",
    "Just Verse": "ただの詩",
    "Letters from a Fugitive": "逃亡者からの手紙",
    "A Novel Method for Invocation & Contrition": "召喚と痛悔の新しい方法",
    "The Radical Measure (Glossed)": "急進的な手段（注釈付き）",
    "The Radical Measure": "急進的な手段",
    "The Red Book of Brittany": "ブルターニュの赤き書",
    "A Tower Rises": "塔が建つ",
    "The Turquoise Hand": "ターコイズの手",
    "Where Has She Gone?": "彼女はどこへ行ったのか？",
    "Ascite Supplications": "腹水の嘆願",
    "Cucurbit Prisoner Records 1928": "ククルビット囚人記録 1928",
    "Echidnalia": "エキドナリア",
    "The Encircling Tantra": "取り囲むタントラ",
    "The Hissing Key": "シューと鳴る鍵",
    "Hunting Journals of Bryan Dewulf": "ブライアン・デウルフの狩猟日記",
    "It Is Written": "それは書かれている",
    "Key of Night": "夜の鍵",
    "Medusa's Lament": "メドゥーサの哀歌",
    "One Hundred And Eight": "百と八",
    "The Queens of the Rivers": "川の女王たち",
    "Recordings from the Althiban Abyss": "アルティバン深淵からの録音",
    "The Republic of Teeth": "歯の共和国",
    "Singlefoot Songs": "片足の歌",
    "Stolen Histories": "盗まれた歴史",
    "The Tantra of Worms": "蛆虫のタントラ",
    "Ud Rocashaas": "ウード・ロカシャース",
    "Against the Sisterhood of the Knot and the Foulness of their Depraved Customs": "結び目の姉妹団とその堕落した習慣の汚らしさに対抗して",
    "Against Vitruvius": "ウィトルウィウスに対抗して",
    "The Book of the White Cat": "白猫の書",
    "Damascene Traditions of the House of Lethe": "レテの家のダマスカスの伝統",
    "De motu corporum vetitorum": "禁じられた物体の運動について",
    "Each Flame His Fuel": "各々の炎が彼の燃料",
    "Eva's Treasury": "エヴァの宝物庫",
    "The Fallen Cross": "堕ちた十字架",
    "The Focus of Amber": "琥珀の焦点",
    "The Humours of a Gentleman": "紳士の気質",
    "In The Mountains As Upon The Plain There May Not Be A Path Where None Has Passed": "誰も通らなかった道は、平野にも山にもない",
    "The Invisible Opera (Unfinished Recording)": "見えないオペラ（未完成の録音）",
    "Journal of Thomas Dewulf": "トーマス・デウルフの日記",
    "The Lion and the Glass": "ライオンと鏡",
    "The Locksmith's Dream: Portions and Proportions": "鍵師の夢：部分と割合",
    "The Locksmith's Dream: Stolen Reflections": "鍵師の夢：盗まれた反射",
    "The Mirror of Melancthe": "メランクテの鏡",
    "On Resonance": "共鳴について",
    "On What is Contained By Silver": "銀に含まれるものについて",
    "Opening the Sky": "空を開く",
    "The Origins of Hours": "時の起源",
    "The Other Eye of the Serpent": "蛇のもう一つの目",
    "Perugian Diaries": "ペルージャの日記",
    "Seven Faces of Icarus": "イカロスの七つの顔",
    "A Seventh Voice": "第七の声",
    "Sunset Celia and the End of Days": "日没のセリアと終わりの日",
    "Travelling at Night, vol 2": "夜の旅、第2巻",
    "A True History of Valentine Dewulf": "ヴァレンタイン・デウルフの真実の歴史",
    "Annals of St Brandan's": "聖ブランダン年代記",
    "The Barrowchild's Elegies": "塚の子供の悲歌",
    "Chione at Abydos": "アビドスのキオネ",
    "Ettery After": "エッタリーの後で",
    "Exercises in the Continuity of Self": "自己の連続性の練習",
    "The Five Letters On Memory": "記憶に関する五通の手紙",
    "In Memory of Gods": "神々の記憶に",
    "An Introduction to Histories": "歴史学入門",
    "The Ivory Book": "象牙の書",
    "Lady Eva's Repose": "エヴァ夫人の休息",
    "Musgrave's Sketches": "マスグレイブのスケッチ",
    "Naenian Sketches": "ネニアのスケッチ",
    "Nyn's Cages (Bruges Text, Illuminated)": "ニンの檻（ブルージュ版、装飾付き）",
    "Oblations in Iron": "鉄の奉納",
    "On the White": "白について",
    "Operations of a Certain Finality": "ある種の最終的な作戦",
    "A Second Glory": "第二の栄光",
    "The Scar in the Sky": "空の傷跡",
    "Those Indignities Perpetrated By the Deceitful Fraternity of Obliviates": "忘却の欺瞞的な兄弟団によって犯されたこれらの屈辱",
    "Towards a Fundamental Aesthetic: Second Edition": "根本的な美学に向けて：第二版",
    "The White Book of Brittany": "ブルターニュの白き書",
    "The World Does Not Weep": "世界は泣かない",
}

def translate_file(filepath, is_books_file=False):
    with open(filepath, 'r') as f:
        data = json.load(f)
        
    items = data if is_books_file else data

    for item in items:
        # Translate main name
        if item.get('name_en') in translation_dict and item.get('name_ja') == item.get('name_en'):
            item['name_ja'] = translation_dict[item['name_en']]
            
        # If memory sources, also translate books inside
        if not is_books_file and 'books' in item:
            for book in item['books']:
                if book.get('name_en') in translation_dict and book.get('name_ja') == book.get('name_en'):
                    book['name_ja'] = translation_dict[book['name_en']]

    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

# Update the two files
translate_file('data/books.json', is_books_file=True)
translate_file('data/memory_sources.json', is_books_file=False)

# also update the frontend copy
translate_file('frontend/public/data/books.json', is_books_file=True)
translate_file('frontend/public/data/memory_sources.json', is_books_file=False)

print("Translation completed successfully.")
